#!/usr/bin/env python3
"""M0 qualification evidence generator — machine-readable status + report."""
from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))


def _git(cmd: list[str]) -> str:
    try:
        return subprocess.check_output(["git", *cmd], cwd=ROOT, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return ""


def _fixture_digest() -> tuple[int, str]:
    fixture_dir = ROOT / "docs" / "competition_contract" / "fixtures"
    paths = sorted(fixture_dir.rglob("*.json")) if fixture_dir.is_dir() else []
    h = hashlib.sha256()
    for p in paths:
        h.update(p.name.encode())
        h.update(p.read_bytes())
    return len(paths), h.hexdigest()[:16] if paths else "none"


def _run_pytest() -> tuple[str, bool, str]:
    cmd = [
        sys.executable,
        "-m",
        "pytest",
        "tests/contract",
        "tests/semantic",
        "tests/runtime",
        "tests/submission",
        "-q",
    ]
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    output = (proc.stdout or "") + (proc.stderr or "")
    return " ".join(cmd), proc.returncode == 0, output.strip()[-2000:]


def _run_soak(games: int) -> tuple[str, dict]:
    from ptcg_ai.eval.arena import ArenaConfig, run_soak_batch
    from ptcg_ai.runtime.runtime import CompetitionRuntime

    deck_path = ROOT / "submission" / "deck.csv"
    deck = [int(x) for x in deck_path.read_text().split() if x.strip()]
    runtime = CompetitionRuntime(deck)
    cmd = f"python tools/qualify_runtime.py --soak-games {games}"
    cfg = ArenaConfig(max_steps=800, time_bank_mode="authoritative", initial_time_seconds=600.0)
    card = run_soak_batch(runtime.act, deck, games=games, sim_root=ROOT / "sample_submission", config=cfg)
    return cmd, card.to_dict()


def _qualification_level(status: dict) -> str:
    gate = [
        not status["source_dirty"],
        status["completed_games"] >= 50,
        status["unsupported_schema_count"] == 0,
        status["illegal_action_count"] == 0,
        status["protocol_error_count"] == 0,
        status["crash_count"] == 0,
        status["fallback_count"] == 0,
    ]
    if all(gate):
        return "qualified"
    if status["completed_games"] >= 1 and status["crash_count"] == 0:
        return "provisional"
    return "not_qualified"


def build_status(*, soak_games: int = 50) -> dict:
    branch = _git(["rev-parse", "--abbrev-ref", "HEAD"])
    head = _git(["rev-parse", "HEAD"])
    dirty = bool(_git(["status", "--porcelain"]))
    fixture_count, fixture_digest = _fixture_digest()
    test_cmd, test_ok, test_output = _run_pytest()
    soak_cmd, soak = _run_soak(soak_games)

    status = {
        "branch": branch,
        "head_commit": head,
        "source_dirty": dirty,
        "python_version": platform.python_version(),
        "os": platform.platform(),
        "simulator_path": str(ROOT / "sample_submission" / "cg" / "game.py"),
        "executed_at": datetime.now(timezone.utc).isoformat(),
        "fixture_count": fixture_count,
        "fixture_digest": fixture_digest,
        "test_command": test_cmd,
        "test_passed": test_ok,
        "test_output_tail": test_output,
        "soak_command": soak_cmd,
        "soak_deck_matchup": "self_play_same_deck",
        "seat_distribution": {"first": soak_games // 2, "second": soak_games - soak_games // 2},
        "completed_games": soak.get("completed_games", 0),
        "unsupported_schema_count": soak.get("unsupported_schema_count", 0),
        "fallback_count": soak.get("fallback_count", 0),
        "illegal_action_count": soak.get("illegal_action_count", 0),
        "protocol_error_count": soak.get("protocol_error_count", 0),
        "crash_count": soak.get("crash_count", 0),
        "time_bank_exhaustion_count": soak.get("time_bank_exhaustion_count", 0),
        "max_rss_bytes": soak.get("max_rss_bytes"),
        "median_decision_ms": soak.get("median_decision_ms"),
        "p95_decision_ms": soak.get("p95_decision_ms"),
        "p99_decision_ms": soak.get("p99_decision_ms"),
        "conservation_unverified_count": soak.get("conservation_unverified_count", 0),
        "conservation_verified_count": soak.get("conservation_verified_count", 0),
    }
    status["qualification_level"] = _qualification_level(status)
    status["reviewed_commit"] = head
    return status


def write_report(status: dict) -> None:
    report_path = ROOT / "docs" / "qualification_reports" / "runtime_v1_implementation_report.md"
    lines = [
        "# Runtime v1 Qualification Report",
        "",
        "> Auto-generated by `tools/qualify_runtime.py`. Do not hand-edit status fields.",
        "",
        f"- **branch**: `{status['branch']}`",
        f"- **HEAD commit**: `{status['head_commit']}`",
        f"- **reviewed_commit**: `{status['reviewed_commit']}`",
        f"- **source_dirty**: `{status['source_dirty']}`",
        f"- **qualification_level**: `{status['qualification_level']}`",
        f"- **executed_at**: {status['executed_at']}",
        f"- **Python**: {status['python_version']}",
        f"- **OS**: {status['os']}",
        f"- **simulator**: `{status['simulator_path']}`",
        "",
        "## Fixtures",
        f"- fixture_count: {status['fixture_count']}",
        f"- fixture_digest: `{status['fixture_digest']}`",
        "",
        "## Tests",
        f"- command: `{status['test_command']}`",
        f"- passed: **{status['test_passed']}**",
        "",
        "## Soak",
        f"- command: `{status['soak_command']}`",
        f"- deck matchup: {status['soak_deck_matchup']}",
        f"- seat distribution: {status['seat_distribution']}",
        f"- completed_games: {status['completed_games']}",
        f"- unsupported_schema_count: {status['unsupported_schema_count']}",
        f"- fallback_count: {status['fallback_count']}",
        f"- illegal_action_count: {status['illegal_action_count']}",
        f"- protocol_error_count: {status['protocol_error_count']}",
        f"- crash_count: {status['crash_count']}",
        f"- time_bank_exhaustion_count: {status['time_bank_exhaustion_count']}",
        f"- max RSS: {status['max_rss_bytes']}",
        f"- decision time median / p95 / p99 (ms): {status['median_decision_ms']} / {status['p95_decision_ms']} / {status['p99_decision_ms']}",
        f"- conservation verified / unverified: {status['conservation_verified_count']} / {status['conservation_unverified_count']}",
        "",
        "## M0 Gate",
        "",
        "| Criterion | Value |",
        "|-----------|-------|",
        f"| commit SHA matches HEAD | {not status['source_dirty']} |",
        f"| source_dirty = false | {not status['source_dirty']} |",
        f"| completed_games >= 50 | {status['completed_games'] >= 50} |",
        f"| unsupported_schema_count = 0 | {status['unsupported_schema_count'] == 0} |",
        f"| illegal_action_count = 0 | {status['illegal_action_count'] == 0} |",
        f"| crash_count = 0 | {status['crash_count'] == 0} |",
        f"| fallback_count = 0 | {status['fallback_count'] == 0} |",
        "",
    ]
    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--soak-games", type=int, default=50)
    parser.add_argument("--skip-soak", action="store_true")
    parser.add_argument("--skip-tests", action="store_true")
    args = parser.parse_args()

    if args.skip_soak and args.skip_tests:
        status = {
            "branch": _git(["rev-parse", "--abbrev-ref", "HEAD"]),
            "head_commit": _git(["rev-parse", "HEAD"]),
            "source_dirty": bool(_git(["status", "--porcelain"])),
            "qualification_level": "not_qualified",
            "fixture_count": 0,
            "completed_games": 0,
            "unsupported_schema_count": 0,
            "fallback_count": 0,
            "illegal_action_count": 0,
            "protocol_error_count": 0,
            "crash_count": 0,
        }
    else:
        status = build_status(soak_games=0 if args.skip_soak else args.soak_games)

    out_json = ROOT / "docs" / "qualification_reports" / "qualification_status.json"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(status, indent=2), encoding="utf-8")
    write_report(status)
    print(json.dumps(status, indent=2))
    if status.get("qualification_level") != "qualified":
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
